---
stages:
  - tests
  - push

variables:
  GITHUB_USER: lotusnoir

###########################
# job dependencies:
#       file: .mega-linter.yml
mega-linter:
  stage: tests
  image: oxsecurity/megalinter:v7
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
  script: ["true"]
  allow_failure: true
  variables:
    DEFAULT_WORKSPACE: ${CI_PROJECT_DIR}

##################################################
# PUSH CODE WHEN ALL TEST OK
##################################################
push_src_on_github:
  stage: push
  image: alpine:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
  before_script:
    - apk add git openssh-client
    - eval $(ssh-agent -s)
    - echo "${GITHUB_USER_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tUser ansible\n\tStrictHostKeyChecking no\n\tForwardAgent yes\n\n" > ~/.ssh/config
    - git config --global user.email "${GITHUB_USER_EMAIL}"
    - git config --global user.name "${GITHUB_USER}"
    - git config --global init.defaultBranch main
    - COMMENT=$(git log -1 --pretty=%B | head -1)
  script:
    - git clone git@github.com:${GITHUB_USER}/packer-unattended_distrib_files.git /tmp/packer-unattended_distrib_files
    - find /tmp/packer-unattended_distrib_files -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf "{}" +;
    - rm -rf .git
    - cp -r . /tmp/packer-unattended_distrib_files/
    - cd /tmp/packer-unattended_distrib_files
    - git add -A
    - git commit -m "${COMMENT}" || echo "No changes, nothing to commit!"
    - git push --follow-tags
