#---
#repos:
#  - repo: https://github.com/oxsecurity/megalinter
#    rev: v6.8.0 # Git tag specifying the hook, not mega-linter-runner, version
#    hooks:
#      - id: megalinter-incremental
#        name: Run MegaLinter (skipping linters that run in project mode)
#        entry: npx --
#        language: system
#        require_serial: true
#        args:
#          - mega-linter-runner
#          - --containername
#          - "megalinter-incremental"
#          - --remove-container
#          - --fix
#          - --env
#          - "'APPLY_FIXES=all'"
#          - --env
#          - "'CLEAR_REPORT_FOLDER=true'"
#          - --env
#          - "'LOG_LEVEL=warning'"
#          - --filesonly
